apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.xdew.ch
spec:
  group: xdew.ch
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "Project display name"
                description:
                  type: string
                  description: "Project description"
                userId:
                  type: string
                  description: "Owner user ID"
              required:
                - name
                - userId
            status:
              type: object
              properties:
                currentState:
                  type: string
                  description: "Current project state"
                lastUpdated:
                  type: string
                  format: date-time
                namespacesCount:
                  type: integer
                  default: 0
                history:
                  type: array
                  items:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                      state:
                        type: string
                      message:
                        type: string
                      user:
                        type: string
                    required:
                      - timestamp
                      - state
                      - message
      additionalPrinterColumns:
        - name: Display Name
          type: string
          jsonPath: .spec.name
        - name: Owner
          type: string
          jsonPath: .spec.userId
        - name: State
          type: string
          jsonPath: .status.currentState
        - name: Workspaces
          type: integer
          jsonPath: .status.namespacesCount
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Cluster
  names:
    plural: projects
    singular: project
    kind: Project

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspaces.xdew.ch
spec:
  group: xdew.ch
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "Workspace display name"
                description:
                  type: string
                  description: "Workspace description"
                projectId:
                  type: string
                  description: "Parent project ID (metadata.name)"
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "projectId is immutable"
                resourceQuota:
                  type: object
                  properties:
                    cpu:
                      type: string
                      default: "2"
                    memory:
                      type: string
                      default: "4Gi"
                    storage:
                      type: string
                      default: "10Gi"
                    pods:
                      type: string
                      default: "10"
              required:
                - name
                - projectId
            status:
              type: object
              properties:
                currentState:
                  type: string
                  enum: ["requested", "accepted", "rejected", "deleted"]
                  default: "requested"
                lastUpdated:
                  type: string
                  format: date-time
                history:
                  type: array
                  items:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                      state:
                        type: string
                      message:
                        type: string
                      user:
                        type: string
                    required:
                      - timestamp
                      - state
                      - message
      additionalPrinterColumns:
        - name: Display Name
          type: string
          jsonPath: .spec.name
        - name: State
          type: string
          jsonPath: .status.currentState
        - name: Project
          type: string
          jsonPath: .spec.projectId
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Cluster
  names:
    plural: workspaces
    singular: workspace
    kind: Workspace
