apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: projects.xdew.ch
spec:
    group: xdew.ch
    versions:
        - name: v1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              name:
                                  type: string
                                  description: "Project display name"
                              description:
                                  type: string
                                  description: "Project description"
                              owner:
                                  type: string
                                  description: "Project owner identifier"
                              teams:
                                  type: array
                                  description: "List of team groups with access"
                                  items:
                                      type: string
                          required:
                              - name
                              - description
                              - owner
                              - teams
                      status:
                          type: object
                          properties:
                              phase:
                                  type: string
                                  enum: ["active", "suspended", "terminated"]
                                  default: "active"
                              workspaceCount:
                                  type: integer
                                  default: 0
                              createdAt:
                                  type: string
                                  format: date-time
                              lastUpdated:
                                  type: string
                                  format: date-time
                              auditLog:
                                  type: array
                                  items:
                                      type: object
                                      properties:
                                          timestamp:
                                              type: string
                                              format: date-time
                                          user:
                                              type: string
                                          action:
                                              type: string
                                          status:
                                              type: string
                                          comment:
                                              type: string
                                      required:
                                          - timestamp
                                          - user
                                          - action
                                          - status
                          required:
                              - phase
                              - workspaceCount
                              - createdAt
                              - lastUpdated
                              - auditLog
          additionalPrinterColumns:
              - name: Display Name
                type: string
                jsonPath: .spec.name
              - name: Owner
                type: string
                jsonPath: .spec.owner
              - name: Phase
                type: string
                jsonPath: .status.phase
              - name: Workspaces
                type: integer
                jsonPath: .status.workspaceCount
              - name: Age
                type: date
                jsonPath: .metadata.creationTimestamp
    scope: Cluster
    names:
        plural: projects
        singular: project
        kind: Project
